<a href="https://colab.research.google.com/github/jonkwiatkowski/deep-learning-challenge/blob/main/AlphabetSoupCharity_Optimzation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Google Colab doesn't come with this package installed, so we'll install it.
!pip install keras-tuner

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: keras-tuner in /usr/local/lib/python3.7/dist-packages (1.1.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (1.21.6)
Requirement already satisfied: kt-legacy in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (1.0.4)
Requirement already satisfied: ipython in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (7.9.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (21.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (2.23.0)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.7/dist-packages (from keras-tuner) (2.9.1)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (57.4.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (0.7.5)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (2.0.10)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (0.2.0)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (0.18.2)
Requirement already satisfied: pexpect in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (5.1.1)
Requirement already satisfied: pygments in /usr/local/lib/python3.7/dist-packages (from ipython->keras-tuner) (2.6.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.7/dist-packages (from jedi>=0.10->ipython->keras-tuner) (0.8.3)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->keras-tuner) (1.15.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->keras-tuner) (0.2.5)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->keras-tuner) (3.0.9)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/dist-packages (from pexpect->ipython->keras-tuner) (0.7.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->keras-tuner) (2022.9.24)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (0.38.4)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (0.4.6)
Requirement already satisfied: grpcio>=1.24.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.50.0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.3.0)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (0.6.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (2.14.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.8.1)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (3.19.6)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (3.4.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from tensorboard->keras-tuner) (1.0.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (5.2.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth<3,>=1.6.3->tensorboard->keras-tuner) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.7/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard->keras-tuner) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.7/dist-packages (from markdown>=2.6.8->tensorboard->keras-tuner) (4.13.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->keras-tuner) (4.1.1)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard->keras-tuner) (3.10.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard->keras-tuner) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard->keras-tuner) (3.2.2)

In [2]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
from google.colab import files
my_file = files.upload()

application_df = pd.read_csv("charity_data.csv")
application_df.head()

Saving charity_data.csv to charity_data (1).csv

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ["EIN", "NAME"])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [4]:
# Determine the number of unique values in each column.
unique = application_df.nunique(axis = 0)
print(unique)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [5]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_counts[application_counts < 300].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df["CLASSIFICATION"].value_counts()
classification_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_not_one = application_df["CLASSIFICATION"].value_counts().loc[lambda x : x > 1]
classification_counts_not_one

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts < 800].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [10]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df_numeric = pd.get_dummies(application_df)
application_df_numeric.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [11]:
# Split our preprocessed data into our features and target arrays
X = application_df_numeric.drop("IS_SUCCESSFUL", axis = 1).values
y = application_df_numeric["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

In [12]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [13]:
def create_model(hp):
    
    # Instantiate a Sequential model
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers.
    activation = hp.Choice('activation', ['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide the number of neurons in first layer and also
    # the activation function. 
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=100,
        step=2), activation=activation, input_dim=43))

    # Allow kerastuner to decide the number of hidden layers and number of 
    # neurons in each one
    for i in range(hp.Int('num_layers', 1, 5)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=100,
            step=2),
            activation=activation))
    
    # Define the output layer
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [14]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=50,
    hyperband_iterations=2)

In [15]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled, y_train, epochs=50, validation_data=(X_test_scaled,y_test))

Trial 180 Complete [00h 01m 47s]
val_accuracy: 0.7262973785400391

Best val_accuracy So Far: 0.7289795875549316
Total elapsed time: 01h 44m 26s

In [16]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'relu',
 'first_units': 43,
 'num_layers': 2,
 'units_0': 69,
 'units_1': 71,
 'units_2': 45,
 'units_3': 57,
 'units_4': 5,
 'tuner/epochs': 17,
 'tuner/initial_epoch': 0,
 'tuner/bracket': 1,
 'tuner/round': 0}

In [17]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5605 - accuracy: 0.7290 - 521ms/epoch - 2ms/step
Loss: 0.560477614402771, Accuracy: 0.7289795875549316

In [18]:
number_input_features = len(X_train[0])
number_input_features

43

In [20]:
number_input_features = len(X_train[0])
number_input_features

# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
hidden_nodes_layer1 = 86
hidden_nodes_layer2 = 43
hidden_nodes_layer3 = 43

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer1, input_dim = number_input_features, activation="relu"))


# Second hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units = hidden_nodes_layer3, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units = 1, activation = "sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_8 (Dense)             (None, 86)                3784

 dense_9 (Dense)             (None, 43)                3741

 dense_10 (Dense)            (None, 43)                1892

 dense_11 (Dense)            (None, 1)                 44

=================================================================
Total params: 9,461
Trainable params: 9,461
Non-trainable params: 0
_________________________________________________________________

In [21]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [22]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs = 50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5672 - accuracy: 0.7220
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5533 - accuracy: 0.7303
Epoch 3/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5506 - accuracy: 0.7310
Epoch 4/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5491 - accuracy: 0.7336
Epoch 5/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5474 - accuracy: 0.7341
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7341
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7356
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7347
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7350
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7353
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7358
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7365
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5424 - accuracy: 0.7369
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7385
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7379
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7381
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7381
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7382
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5402 - accuracy: 0.7395
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7391
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7386
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7378
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7386
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7387
Epoch 25/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7403
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7392
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7379
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7399
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7401
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7389
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7393
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7391
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7390
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7404
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7389
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7397
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7407
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7402
Epoch 39/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7405
Epoch 40/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5358 - accuracy: 0.7406
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7411
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7406
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7409
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7416
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7413
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7404
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7402
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5351 - accuracy: 0.7410
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7410
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5344 - accuracy: 0.7409

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5667 - accuracy: 0.7234 - 460ms/epoch - 2ms/step
Loss: 0.5666706562042236, Accuracy: 0.7233819365501404

In [24]:
# Export our model to HDF5 file
nn.save("AlphabetSoupCharity_Optimization.h5")